version: 2
jobs:
   build:
     docker:
       - image: circleci/node:8.11
     environment:
       - NODE_ENV: "test"
       - DEBUG: "*"
     steps:
       - checkout
       - restore_cache:
           key: yarn-{{ checksum "yarn.lock" }}
       - run: yarn install
       - save_cache:
           key: yarn-{{ checksum "yarn.lock" }}
           paths:
             - node_modules
       - run: yarn lint --debug
       - run: yarn test
       - run:
           name: npm audit
           command: |
             sudo npm install -g npm
             npm install --package-lock-only
             set +e
             npm audit | tee .npm-audit-tmp
             if grep -e "found [0-9]* critical vulnerabilit" -e "found [0-9]*.*[0-9]* critical" .npm-audit-tmp -q; then
               echo "Detected dependencies with critical vulnerabilities. Replace or upgrade before deploying"
               exit 1
             fi
       - run:
           name: Clean after npm audit
           command: rm ./package-lock.json .npm-audit-tmp
           when: always
